/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "callBack.h"


void
callback_1_clnt(char *host, int result, char* data, int stream)
{
	CLIENT *clnt;
	void  *result_1;
	int sendresult_1_result = result;
	void  *result_2;
	int returndata_1_stream=stream;
	char *returndata_1_data = data;

#ifndef	DEBUG
	clnt = clnt_create (host, callBack, v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_2 = returndata_1(returndata_1_stream, returndata_1_data, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	if(stream<0) {
		result_1 = sendresult_1(sendresult_1_result, clnt);
		if (result_1 == (void *) NULL) {
			clnt_perror(clnt, "call failed");
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}