/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "callBack.h"

bool_t
xdr_returndata_1_argument (XDR *xdrs, returndata_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->stream))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->data, 1024))
		 return FALSE;
	return TRUE;
}
