/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "callBack.h"
#include <unistd.h>

void *
sendresult_1_svc(int result,  struct svc_req *rqstp)
{
	static char * result1;
	result1 = &result;

	printf("result %d\n", result);
	/*
	 * insert server code here
	 */

	return (void *) &result1;
}

void *
returndata_1_svc(int stream, char *data,  struct svc_req *rqstp)
{
	static char * result;
	printf("%d: %s\n", stream, data);
	/*
	 * insert server code here
	 */

	return (void *) &result;
}
