/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remoteCall.h"


void
remotecallprog_1(char *host, char* command)
{
	CLIENT *clnt;
	int  *result_1;
	char *remotecallproc_1_command = command;

#ifndef	DEBUG
	clnt = clnt_create (host, remoteCallProg, v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = remotecallproc_1(remotecallproc_1_command, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host command\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	remotecallprog_1 (host, argv[2]);
exit (0);
}
