/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REMOTECALL_H_RPCGEN
#define _REMOTECALL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define remoteCallProg 0x20000001
#define v1 1

#if defined(__STDC__) || defined(__cplusplus)
#define remoteCallProc 1
extern  int * remotecallproc_1(char *, CLIENT *);
extern  int * remotecallproc_1_svc(char *, struct svc_req *);
extern int remotecallprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define remoteCallProc 1
extern  int * remotecallproc_1();
extern  int * remotecallproc_1_svc();
extern int remotecallprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REMOTECALL_H_RPCGEN */
