/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remoteCall.h"

int *
remotecallproc_1_svc(char *command,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 result = system(command);

	return &result;
}
